# Generated by Django 3.0.5 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=64)),
                ('tz', models.CharField(max_length=128)),
                ('start_datetime', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
